spring:
  datasource:
    url: jdbc:postgresql://89.111.174.153:5432/social-network-account
    username: postgres
    password: postgres
    hikari:
      schema: account_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS account_schema
      connection-timeout: 10000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: 89.111.174.153:9093

app:

  kafka:
    kafkaAuthTopic: "auth-topic"
    kafkaMessageGroupId: "kafka-message-group-id"